config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  root to: 'items#index'
  resources :users, only: [:index, :show, :edit, :update] do
    resources :orders
    resources :cards, except: :edit
  end
  resources :orderitems, only: :index
  namespace :adm do
    resources :users
    resources :orders
    resources :orderitems, only: :index
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :categories
  resources :items do
    collection do
      get 'search'
    end
  end
  # resources :orders
  # resources :orderitems, only: :index
  
  post 'orders', to: 'orders#create'
  post 'cartitems', to: 'orderitems#create'
  delete 'cartdelete', to: 'orderitems#destroy'
  # get '/cateindex', to: 'categories#cateindex'
  # post '/cartitems', to: 'carts#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :orderitem
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items

  validates :code, presence: true, uniqueness: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category, optional: true
  has_many :orderitems

  validates :category, presence: true
  validates :code, presence: true, uniqueness: true, length: { maximum:13 } 
  validates :name, presence: true
  validates :price, presence: true
  validates :taxrate, presence: true

  mount_uploader :image, ImageUploader
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :orderitem, dependent: :destroy
  belongs_to :user

  # def oreder_sum(tax)
  #   tax0sum = 0
  #   tax8sum = 0
  #   tax10sum = 0
  #   itempqsum = 0
  #   @cart.each do |item|
  #     p = item.itemprice
  #     q = item.quantity
  #     itempq = p * q
  #     tax = item.item.taxrate


end

app/models/orderitem.rb
class Orderitem < ApplicationRecord
  belongs_to :item, optional:true
  belongs_to :cart, optional: true
  belongs_to :order, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders
  has_many :cards
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  require "payjp"
  before_action :user_login, only:[:index, :new, :create, :delete, :show]
  before_action :set_card

  # def index
  #   card = Card.find_by(user_id: current_user.id)
  #   if card.blank?
  #     redirect_to action: "new"
  #   else
  #     Payjp.api_key = Rails.application.credentials.dig(:payjp, :secret_key)
  #     customer = Payjp::Customer.retrieve(card.customer_id)
  #     @default_card_information = customer.cards.retrieve(card.card_id)
  #   end
  # end

  def index
    if @card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :secret_key)
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  def new
    # if Card.find_by(user_id: current_user.id).present?
    #   redirect_to action: :show
    # else
    @card = Card.new  
    # end
  end

  def create
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :secret_key)
    customer = Payjp::Customer.create(
      email: current_user.email,
      card: params[:card_token],
      metadata: {user_id: current_user.id}
    )
    @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
    if @card.save
      redirect_to action: :index
    else
      redirect_to action: :new
    end
  end

  def destroy
    card = Card.find_by(user_id: current_user.id)
    if card.blank?
    else
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :secret_key)
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
    redirect_to action: "new"
  end

  private

  def user_login
    redirect_to new_user_session_path unless user_signed_in?
  end

  def set_card
    @card = Card.where(user_id: current_user.id).first if Card.where(user_id: current_user.id).present?
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_category, only: [:index, :show, :new, :edit]
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :set_cart, only: [:index, :show]
  before_action :move_to_index, except: [:index, :show]

  def index
    @items = Item.all
  end

  def show
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.create(item_params)
  end

  def edit
  end

  def update
    @item.update(item_params)
  end

  def destroy
    @item.destroy
  end

  private
  def item_params
    params.require(:item).permit(:category_id, :code, :name, :image, :price, :taxrate)
  end

  def set_category
    @categories = Category.all
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def set_cart
    if session[:cart_id]
      @cart_id = session[:cart_id]
      @cart = Orderitem.where(cart_id: @cart_id)
    end
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    user = User.find(params[:id])
    @orders = user.orders
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orderitems_helper.rb
module OrderitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_notification.html.haml
.notification
  - flash.each do |key, value|
    =content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title EcSample
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/shared/_adheader.html.haml
.adheader
  .adheader__title
    ECshop管理画面
  .adheader__nav
    .adheader__nav__left
      .adheader__nav__left__list
        = link_to "受注管理", adm_orders_path
      .adheader__nav__left__list
        = link_to "商品登録", new_item_path 
      .adheader__nav__left__list
        -# = link_to "商品検索"  
      .adheader__nav__left__list
        = link_to "部門管理", new_category_path
    .adheader__nav__right
      .adheader__nav__right__list
        = link_to "管理画面トップへ", new_item_path
      .adheader__nav__right__list
        = link_to "ショップホームページへ", root_path
      = link_to " . ", adm_users_path

app/views/shared/_calcsum.html.haml
- if session[:cart_id]
  - if @cart.length > 0
    .cartitems
      - price_sum = 0
      - quantity_sum = 0
      - @cart.each do |item|
        - price = item[:itemprice]
        - quantity = item[:quantity]
        - price_sum += price * quantity
        - quantity_sum += quantity
      .cartitems__output
        カートの中の商品: #{@cart.length}品目、#{quantity_sum}点、小計#{price_sum}円(税抜)  
      .cartitems__delete
        = link_to 'カートを空にする', cartdelete_path(@cart), method: :delete

app/views/shared/_footer.html.haml
%footer
  .footer
    .footer__contents
      送料一律 400円+税 &nbsp&nbsp&nbspsampleID: test@test.com &nbsp&nbspsamplePassword: test1234
    .footer__rights
      (c)

app/views/shared/_header.html.haml
%header 
  .header
    .header__left
      .header__left__title
        = link_to "ネットショップサンプルサイト", root_path 
      - if user_signed_in?
        .header__left__user
          = current_user.name + ' 様'
    .header__right
      .header__right__nav
        - if user_signed_in?
          -# 
          %ul
            %li
              = link_to "注文に進む", new_user_order_path(current_user), class: "header-menu-btn"
            %li
              %span
                マイページ
                %ul
                  %li
                    = link_to "注文履歴", user_orders_path(current_user)
                  %li
                    = link_to "アカウント", edit_user_registration_path(current_user)
                  %li
                    = link_to "カード情報", user_cards_path(current_user)
                  %li
                    = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header__right__nav__logout"
                  - if current_user.admin?
                    %li
                      = link_to "管理者", new_item_path
        - else
          %ul
            %li
              = link_to "ログイン", new_user_session_path, class: "header-menu-btn"
            %li 
              = link_to "新規登録", new_user_registration_path, class: "header-menu-btn"

app/views/shared/_sidebar.html.haml
.sidebar
  .sidebar__box
    .sidebar__box__categories
      - @categories.each do |c|
        .sidebar__box__categories__category
          = link_to c.name, category_path(c), class: "category-line"
    -# - if user_signed_in? && current_user.admin?
    -#   .sidebar__admin
    -#     = link_to "商品登録", new_item_path