config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  root to: 'items#index'
  resources :users, only: [:index, :show, :edit, :update] do
    resources :orders
    resources :cards, except: :edit
  end
  resources :orderitems, only: :index
  namespace :adm do
    resources :users
    resources :orders
    resources :orderitems, only: :index
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :categories
  resources :items do
    collection do
      get 'search'
    end
  end
  # resources :orders
  # resources :orderitems, only: :index
  
  post 'orders', to: 'orders#create'
  post 'cartitems', to: 'orderitems#create'
  delete 'cartdelete', to: 'orderitems#destroy'
  # get '/cateindex', to: 'categories#cateindex'
  # post '/cartitems', to: 'carts#create'

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category, optional: true
  has_many :orderitems

  validates :category, presence: true
  validates :code, presence: true, uniqueness: true, length: { maximum:13 } 
  validates :name, presence: true
  validates :price, presence: true
  validates :taxrate, presence: true

  mount_uploader :image, ImageUploader
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_category, only: [:index, :show, :new, :edit]
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :set_cart, only: [:index, :show]
  before_action :move_to_index, except: [:index, :show]

  def index
    @items = Item.all
  end

  def show
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.create(item_params)
  end

  def edit
  end

  def update
    @item.update(item_params)
  end

  def destroy
    @item.destroy
  end

  private
  def item_params
    params.require(:item).permit(:category_id, :code, :name, :image, :price, :taxrate)
  end

  def set_category
    @categories = Category.all
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def set_cart
    if session[:cart_id]
      @cart_id = session[:cart_id]
      @cart = Orderitem.where(cart_id: @cart_id)
    end
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_adheader.html.haml
.adheader
  .adheader__title
    ECshop管理画面
  .adheader__nav
    .adheader__nav__left
      .adheader__nav__left__list
        = link_to "受注管理"
      .adheader__nav__left__list
        = link_to "商品登録", new_item_path 
      .adheader__nav__left__list
        = link_to "商品検索"
    .adheader__nav__right
      .redirect__adtop
        = link_to "管理画面トップへ", new_item_path

app/views/items/_itemform.html.haml
.item__new__box
  = form_with(model: @item, local: true) do |f|
    .item__new__box__input
      = f.label :category_id, "部門名:", class: 'item__new__label'
      = f.collection_select :category_id, @categories, :id, :name, include_blank: true, class: 'item__new__field__s'
    .item__new__box__input
      = f.label :code, "商品コード:", class: 'item__new__label'
      = f.text_field :code, class: 'item__new__field__m'
    .item__new__box__input
      = f.label :name, "商品名:", class: 'item__new__label'
      = f.text_field :name, class: 'item__new__field'
    .item__new__box__input
      = f.label :price, "価格:", class: 'item__new__label'
      = f.text_field :price, class: 'item__new__field__s'
    .item__new__box__input
      = f.label :taxrate, "税率:", class: 'item__new__label'
      = f.text_field :taxrate, class: 'item__new__field__s'
    .item__new__box__image
      = f.label :image, "画像:", class: 'item__new__label'
      %label#image-view
        - if @item.image.present?
          = image_tag @item.image.url, class: 'item__new__box__image--view'
        = f.file_field :image, class: 'item__new__box__image--file'
    .item__new__box__submit
      = f.submit "保存する", class: 'item__new__box__submit--btn', id: 'wwwww'

app/views/items/_itemshow.html.haml
.show
  - if flash[:notice]
    = render 'layouts/notification'
  - if @cart
    = render "shared/calcsum" 
  .show__item
    .show__item__detail
      .show__item__detail__name
        = @item.name
      .show__item__detail__price
        本体価格 :
        %span #{@item.price} 円
      .show__item__detail__image__box
        = image_tag @item.image.url, alt: @item.name, class: "show__item__detail__image__box__image" if @item.image.present?
      .show__item__detail__order
        .show__item__detail__order__box
          = form_with(url: cartitems_path, local: true) do |f|
            = f.hidden_field :item_id, value: @item.id, class: "main__items__item__order__id"
            = f.hidden_field :itemcode, value: @item.code, class: "show__item__detail__order__box__code"
            = f.hidden_field :itemname, value: @item.name, class: "show__item__detail__order__box__name"
            = f.hidden_field :itemprice, value: @item.price, class: "show__item__detail__order__box__price"
            = f.number_field :quantity, min:"1", max:"10",class: "show__item__detail__order__box__quantity"
            = f.submit 'カートに入れる', class: "show__item__detail__order__box__cartin"  
  - if user_signed_in? && current_user.admin?
    .show__item__admin
      = link_to "商品編集", edit_item_path

app/views/items/_main.html.haml
.main
  - if flash[:notice]
    = render 'layouts/notification'
  - if @cart
    = render "shared/calcsum"

  .main__items 
    - @items.each do |item|
      .main__items__item
        = link_to item_path(item) do
          .main__items__item__imgbox
            = image_tag item.image.url, alt: item.name, class: "main__items__item__imgbox__image" if item.image.present?
          .main__items__item__name
            = item.name
        .main__items__item__price
          本体価格<br>
          %span
            = "#{item.price} 円"
        .main__items__item__order
          = form_with(url: cartitems_path, local: true, class: "main__items__item__order__form") do |f|
            = f.hidden_field :item_id, value: item.id, class: "main__items__item__order__id"
            = f.hidden_field :itemcode, value: item.code, class: "main__items__item__order__code"
            = f.hidden_field :itemname, value: item.name, class: "main__items__item__order__name"
            = f.hidden_field :itemprice, value: item.price, class: "main__items__item__order__price"
            = f.number_field :quantity, min:"1", max:"10",class: "main__items__item__order__quantity"
            = f.submit 'カートに入れる', class: "main__items__item__order__cartin"

app/views/items/create.html.haml
= render "shared/adheader"
.item__create
  .item__create__message
    - if @item.errors.any?
      - @item.errors.full_messages.each do |message|
        = message
        %br
    - else
      商品登録が完了しました。
  .item__create__box

  .item__create__redirect
    

app/views/items/destroy.html.haml
= render "shared/adheader"
.item__delete
  商品を削除しました。<br>
  = "#{@item.code} #{@item.name}"

app/views/items/edit.html.haml
= render "shared/adheader"
.item__new
  .item__new__title
    商品編集
  = render "itemform"
  .item__delete
    %button
      = link_to '商品を削除する', item_path(@item), method: :delete

app/views/items/index.html.haml
.wrapper
  = render "shared/header"
  = render "shared/sidebar"
  = render "main"
  = render "shared/footer"
  

app/views/items/new.html.haml
= render "shared/adheader"
.item__new
  .item__new__title
    商品新規登録
  = render "itemform"

app/views/items/show.html.haml
.wrapper
  = render "shared/header"
  = render "shared/sidebar"
  = render "itemshow"
  = render "shared/footer"

app/views/items/update.html.haml
= render "shared/adheader"
.item__create
  .item__create__message
    - if @item.errors.any?
      - @item.errors.full_messages.each do |message|
        = message
        %br
    - else
      商品編集が完了しました。
  .item__create__box