config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  root to: 'items#index'
  resources :users, only: [:index, :show, :edit, :update] do
    resources :orders
    resources :cards, except: :edit
  end
  resources :orderitems, only: :index
  namespace :adm do
    resources :users
    resources :orders
    resources :orderitems, only: :index
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :categories
  resources :items do
    collection do
      get 'search'
    end
  end
  # resources :orders
  # resources :orderitems, only: :index
  
  post 'orders', to: 'orders#create'
  post 'cartitems', to: 'orderitems#create'
  delete 'cartdelete', to: 'orderitems#destroy'
  # get '/cateindex', to: 'categories#cateindex'
  # post '/cartitems', to: 'carts#create'

end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  require "payjp"
  before_action :user_login, only:[:index, :new, :create, :delete, :show]
  before_action :set_card

  # def index
  #   card = Card.find_by(user_id: current_user.id)
  #   if card.blank?
  #     redirect_to action: "new"
  #   else
  #     Payjp.api_key = Rails.application.credentials.dig(:payjp, :secret_key)
  #     customer = Payjp::Customer.retrieve(card.customer_id)
  #     @default_card_information = customer.cards.retrieve(card.card_id)
  #   end
  # end

  def index
    if @card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :secret_key)
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  def new
    # if Card.find_by(user_id: current_user.id).present?
    #   redirect_to action: :show
    # else
    @card = Card.new  
    # end
  end

  def create
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :secret_key)
    customer = Payjp::Customer.create(
      email: current_user.email,
      card: params[:card_token],
      metadata: {user_id: current_user.id}
    )
    @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
    if @card.save
      redirect_to action: :index
    else
      redirect_to action: :new
    end
  end

  def destroy
    card = Card.find_by(user_id: current_user.id)
    if card.blank?
    else
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :secret_key)
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
    redirect_to action: "new"
  end

  private

  def user_login
    redirect_to new_user_session_path unless user_signed_in?
  end

  def set_card
    @card = Card.where(user_id: current_user.id).first if Card.where(user_id: current_user.id).present?
  end

end

app/helpers/card_helper.rb
module CardHelper
end

app/views/cards/edit.html.haml
-# .card-info__head
-#   クレジットカード情報入力
-# .card-info__content
-#   = form_with model: [current_user, @card], local: true, html: { id: 'inputForm' } do |f|
-#     .card-form
-#       .card-form__number
-#         = f.label :card_number, "カード番号", class: "card-form__number--label"
-#         %span.card-form__number--require 必須
-#         = f.text_field :card_number, id: "card_number", type: "text", maxlength: "16", placeholder: "半角数字のみ", class: "card-form__number--field"
-#         -# %ul.card-list
-#         -#   %li
-#         -#     = image_tag("logo/logo_visa.gif")
-#         -#   %li
-#         -#     = image_tag("logo/logo_mastercard.gif")
-#         -#   %li
-#         -#     = image_tag("logo/jcb-logomark-img-01.gif")
-#         -#   %li
-#         -#     = image_tag("logo/amex-logomark-img-04.gif")
-#         -#   %li
-#         -#     = image_tag("logo/diners-logomark-img-01.gif")
-#         -#   %li
-#         -#     = image_tag("logo/discover-logomark-img-08.gif")
-#       .card-form__expire
-#         = f.label :expire, "有効期限", class: "card-form__expire--label" 
-#         %span.card-form__expire--require 必須
-#         %br
-#         -# .card-form__expire--date
-#         = f.select :exp_month, [["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],{} , class: 'card-form__expire--month', id: 'exp_month'
-#         %span.expire-month 月
-#         -# %br
-#         -# .card-form__expire--date
-#         = f.select :exp_year, [["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029]],{} , class: 'card-form__expire--year', id: 'exp_year'
-#         %span.expire-year 年
-#       .card-form__security
-#         = f.label :security_code, "セキュリティコード", class: "card-form__security--label"
-#         %span.card-form__security--require 必須
-#         = f.text_field :cvc, id: "cvc", maxlength: "4", placeholder: "カード背面4桁もしくは3桁の番号", class: "card-form__security--field"
-#         .card-form__security--explain
-#           %span>  ?
-#           カード裏面の番号とは?
-#       .card-form__btn
-#       #card_token
-#         = f.submit "追加する", class: "card-form__btn--submit", id: "token_submit"
        

app/views/cards/index.html.haml
.card-info__content__title
  クレジットカード登録情報
  .card-info__content__list
    = form_with model: [current_user, @card], method: :delete, local: true, id: 'charge-form' do |f|
      .card-info__content__list__detail
        = "**** **** ****" + @default_card_information.last4
        %br
        - exp_month = @default_card_information.exp_month.to_s
        - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
        = exp_month + " / " + exp_year
        %input{type: "hidden", name: "card_id", value: ""}
      .card-info__content__list__delete
        = f.submit "削除する", {class: "card-info__content__list__delete--btn"}
      = link_to "ショップに戻る", root_path  
      -# .card-info__content__add
      -#   = link_to new_card_path, class: "card-info__content__add--btn" do
      -#     = icon('far', 'credit-card', class: "card-icon")
      -#     クレジットカードを追加する
      -# .card-info__content__help
      -#   = link_to "#", class: "card-info__content__help--link" do
      -#     支払い方法について
      -# = icon('fas', 'chevron-right', class: "arrow-right-icon")

app/views/cards/new.html.haml
.card-info__head
  クレジットカード情報入力
.card-info__content
  = form_with model: [current_user, @card], local: true, html: { id: 'inputForm' } do |f|
    .card-form
      .card-form__number
        = f.label :card_number, "カード番号", class: "card-form__number--label"
        %span.card-form__number--require 必須
        = f.text_field :card_number, id: "card_number", type: "text", maxlength: "16", placeholder: "半角数字のみ", class: "card-form__number--field"
        -# %ul.card-list
        -#   %li
        -#     = image_tag("logo/logo_visa.gif")
        -#   %li
        -#     = image_tag("logo/logo_mastercard.gif")
        -#   %li
        -#     = image_tag("logo/jcb-logomark-img-01.gif")
        -#   %li
        -#     = image_tag("logo/amex-logomark-img-04.gif")
        -#   %li
        -#     = image_tag("logo/diners-logomark-img-01.gif")
        -#   %li
        -#     = image_tag("logo/discover-logomark-img-08.gif")
      .card-form__expire
        = f.label :expire, "有効期限", class: "card-form__expire--label" 
        %span.card-form__expire--require 必須
        %br
        -# .card-form__expire--date
        = f.select :exp_month, [["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],{} , class: 'card-form__expire--month', id: 'exp_month'
        %span.expire-month 月
        -# %br
        -# .card-form__expire--date
        = f.select :exp_year, [["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029]],{} , class: 'card-form__expire--year', id: 'exp_year'
        %span.expire-year 年
      .card-form__security
        = f.label :security_code, "セキュリティコード", class: "card-form__security--label"
        %span.card-form__security--require 必須
        = f.text_field :cvc, id: "cvc", maxlength: "4", placeholder: "カード背面4桁もしくは3桁の番号", class: "card-form__security--field"
        .card-form__security--explain
          %span>  ?
          カード裏面の番号とは?
      .card-form__btn
      #card_token
        = f.submit "追加する", class: "card-form__btn--submit", id: "token_submit"
      = link_to "ショップに戻る", root_path
        