config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  root to: 'items#index'
  resources :users, only: [:index, :show, :edit, :update] do
    resources :orders
    resources :cards, except: :edit
  end
  resources :orderitems, only: :index
  namespace :adm do
    resources :users
    resources :orders
    resources :orderitems, only: :index
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :categories
  resources :items do
    collection do
      get 'search'
    end
  end
  # resources :orders
  # resources :orderitems, only: :index
  
  post 'orders', to: 'orders#create'
  post 'cartitems', to: 'orderitems#create'
  delete 'cartdelete', to: 'orderitems#destroy'
  # get '/cateindex', to: 'categories#cateindex'
  # post '/cartitems', to: 'carts#create'

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items

  validates :code, presence: true, uniqueness: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :destroy]
  before_action :set_categoryall, only: [:index, :show, :create, :edit]
  before_action :move_to_index, except: :show

  def index
    @category = Category.new
  end

  def show
    if session[:cart_id]
      @cart = Orderitem.where(cart_id: current_cart)
    end
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(category_params)
    redirect_to categories_path, notice: '部門登録が完了しました。'
    # render "index", notice: '部門登録が完了しました。'
  end

  def edit
  end

  def update
    category = Category.find(params[:id])
    category.update(category_params)
    redirect_to categories_path, notice: '部門編集が完了しました'
  end

  def destroy
    @category.destroy
  end

  private
  def category_params
    params.require(:category).permit(:code, :name)
  end

  def set_category
    @category = Category.find(params[:id])
  end

  def set_categoryall
    @categories = Category.all
  end

  def move_to_index
    redirect_to root_path unless user_signed_in? && current_user.admin?
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_categorymain.html.haml
.main
  - if @cart
    = render "shared/calcsum"
  .main__category  
    #{@category.name}の商品一覧
  .main__items
    - @category.items.each do |item|
      .main__items__item
        = link_to item_path(item) do
          .main__items__item__imgbox
            = image_tag item.image.url, alt: item.name, class: "main__items__item__imgbox__image" if item.image.present?
        .main__items__item__name
          = link_to "#{item.name}", item_path(item)
        .main__items__item__price
          本体価格<br>
          = "#{item.price} 円"
        .main__items__item__order
          = form_with(url: cartitems_path, local: true, class: "main__items__item__order__form") do |f|
            = f.hidden_field :item_id, value: item.id, class: "main__items__item__order__id"
            = f.hidden_field :itemcode, value: item.code, class: "main__items__item__order__code"
            = f.hidden_field :itemname, value: item.name, class: "main__items__item__order__name"
            = f.hidden_field :itemprice, value: item.price, class: "main__items__item__order__price"
            = f.number_field :quantity, min:"1", max:"10",class: "main__items__item__order__quantity"
            = f.submit 'カートに入れる', class: "main__items__item__order__cartin"

app/views/categories/destroy.html.haml
= render "shared/adheader"
.item__delete
  部門を削除しました。<br>
  = "部門番号: #{@category.code}   部門名: #{@category.name}"

app/views/categories/edit.html.haml
= render "shared/adheader"
.category
  .category__registration
    .category__registration__update
      部門編集
      .category__registration__update__list
        = form_with(model: @category , local:true) do |f|   
          = f.text_field :code, class: "category__registration__field__s"
          = f.text_field :name, class: "category__registration__field__l"
          = f.submit "保存する", class: "category__registration__submit-btn"
          %button
            = link_to '部門を削除する', "/categories/#{@category.id}", method: :delete
        

app/views/categories/index.html.haml
= render "shared/adheader"
.category
  - if @category.errors.any?
    - @category.errors.full_messages.each do |message|
      = message
      %br
  - else
    - if flash[:notice]
      = render 'layouts/notification'
  .category__registration
    部門一覧
    %table
      %tr
        %th 部門番号
        %th 部門名
        %th
      - @categories.each do |cate|
        %tr
          %td #{cate.code}
          %td #{cate.name}
          %td
            %button
              = link_to '編集する', edit_category_path(cate.id), class: "category__registration__submit-btn"

app/views/categories/new.html.haml
= render "shared/adheader"
.category
  .category__title
    部門新規登録
  .category__registration
    = form_with(model: @category, local: true) do |f|
      .category__registration__input
        = f.label :code, "部門番号:", class: "category__registration__label"
        = f.text_field :code, class: "category__registration__field__s"
      .category__registration__input
        = f.label :name, "部門名:", class: "category__registration__label"
        = f.text_field :name, class: "category__registration__field__l"
      .category__registration__submit
        = f.submit "保存する", class: "category__registration__submit-btn"
  .category__edit
    %button
      = link_to '部門編集画面へ', "/categories/#{@category.id}"

app/views/categories/show.html.haml
= render "shared/header"
= render "shared/sidebar"
= render "categorymain"
= render "shared/footer"